/**
 * Projects — da Behance (behance.net/andreapiscioneri) e apdesign.altervista.org
 * Immagini reali pescate direttamente dai rispettivi progetti.
 */

export interface ProjectImage {
  src: string
  alt: string
  w?: number
  h?: number
}

export interface Project {
  slug: string
  title: string
  client: string
  year: string
  category: string[]
  role: string[]
  stack: string[]
  cover: string
  gallery: ProjectImage[]
  url?: string
  excerpt: string
  description: string
  highlights: string[]
  featured?: boolean
}

const B = 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp'
const BO = 'https://mir-s3-cdn-cf.behance.net/projects/original'

export const projects: Project[] = [
  // ─── BEHANCE ────────────────────────────────────────────────────────────────
  {
    slug: 'iconic-zine',
    title: 'ICONIC ZINE',
    client: 'Progetto personale',
    year: '2025',
    category: ['Magazine', 'Brand Identity', 'Graphic Design'],
    role: ['Graphic Designer', 'Art Director'],
    stack: ['Adobe Illustrator', 'InDesign', 'Photoshop', 'Figma'],
    cover: `${B}/5d33bd235333065.68d4ed0e4d1e0.jpg`,
    gallery: [
      { src: `${B}/5d33bd235333065.68d4ed0e4d1e0.jpg`, alt: 'ICONIC ZINE — cover' },
      { src: `${B}/e74b13235333065.68d4ed0e4ecaa.jpg`, alt: 'ICONIC ZINE — spread 1' },
      { src: `${B}/b98e2b235333065.68d4ed0e4b62f.jpg`, alt: 'ICONIC ZINE — spread 2' },
      { src: `${B}/337a35235333065.68d4ed0e53c33.jpg`, alt: 'ICONIC ZINE — dettaglio' },
      { src: `${B}/255d86235333065.68d4ed0e500a9.jpg`, alt: 'ICONIC ZINE — branding' },
      { src: `${B}/85a4d4235333065.68d4ed0e4bf24.jpg`, alt: 'ICONIC ZINE — social' },
      { src: `${B}/e02b97235333065.68d4ed0e5096c.jpg`, alt: 'ICONIC ZINE — logo' },
    ],
    url: 'https://www.behance.net/gallery/235333065/ICONIC-ZINE',
    excerpt: 'Magazine design con forte identità visiva, branding e visual identity.',
    description: 'ICONIC ZINE è un progetto di magazine design che esplora la costruzione di un\'identità visiva forte e coerente. Il lavoro comprende la progettazione editoriale del magazine, il sistema di branding, la visual identity, il logo design e le declinazioni per i social media.',
    highlights: [
      'Brand identity completa per il magazine',
      'Layout editoriale con sistema tipografico proprietario',
      'Declinazioni visual per social media',
      'Logo design e sistema iconografico',
    ],
    featured: true,
  },
  {
    slug: 'xcuse-me',
    title: 'XCUSE ME',
    client: 'Progetto personale',
    year: '2025',
    category: ['UI/UX', 'Mobile App', 'Prototype'],
    role: ['UX/UI Designer', 'Prototyper'],
    stack: ['Figma', 'Photoshop', 'Protopie'],
    cover: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_632_webp/520670235332807.68d4ec0f04be2.png',
    gallery: [
      { src: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_632_webp/520670235332807.68d4ec0f04be2.png', alt: 'XCUSE ME — UI overview' },
    ],
    url: 'https://www.behance.net/gallery/235332807/XCUSE-ME',
    excerpt: 'Prototipo di app mobile con UI design e user experience curata in Figma e Protopie.',
    description: 'XCUSE ME è un progetto di UI/UX design per un\'applicazione mobile, realizzato interamente in Figma con prototyping avanzato in Protopie. Il progetto si concentra sulla progettazione dell\'interfaccia utente, sull\'esperienza di navigazione e sulle micro-interazioni.',
    highlights: [
      'UI design completo per app mobile',
      'Prototipo interattivo in Protopie',
      'User experience ottimizzata per touch',
      'Design system con componenti riutilizzabili',
    ],
    featured: false,
  },
  {
    slug: 'lumyn',
    title: 'LUMYN — AI Chatbot per E-commerce',
    client: 'Tesi Magistrale — LABA Brescia',
    year: '2025',
    category: ['AI', 'E-commerce', 'UI/UX', 'Web Design'],
    role: ['UX/UI Designer', 'Front-End Developer', 'Researcher'],
    stack: ['Figma', 'Vue.js', 'React', 'Visual Studio Code'],
    cover: `${B}/45d33f235104961.68d0fe39f1f17.jpg`,
    gallery: [
      { src: `${B}/45d33f235104961.68d0fe39f1f17.jpg`, alt: 'LUMYN — hero' },
      { src: `${B}/577d3f235104961.68d0fe39eaff8.jpg`, alt: 'LUMYN — chat UI' },
      { src: `${B}/8c0fba235104961.68d0fe39ed752.jpg`, alt: 'LUMYN — product discovery' },
      { src: `${B}/243ea7235104961.68d0fe39f343b.jpg`, alt: 'LUMYN — checkout flow' },
      { src: `${B}/5b2b5b235104961.68d0fe39ecd88.jpg`, alt: 'LUMYN — mobile' },
      { src: `${B}/146554235104961.68d0fe39ef4e2.jpg`, alt: 'LUMYN — design system' },
    ],
    url: 'https://www.behance.net/gallery/235104961/LUMYN-AI-CHATBOT',
    excerpt: 'Tesi magistrale 110/110 con Lode: AI chatbot conversazionale per e-commerce sviluppato in Vue.js.',
    description: 'Lumyn è il mio progetto di tesi della Laurea Magistrale in Digital Design & Communication presso LABA Brescia (110/110 con Lode). Un AI chatbot conversazionale per e-commerce capace di accompagnare l\'utente nella scoperta prodotto, consigliare alternative e completare l\'ordine in-chat.',
    highlights: [
      'Tesi Magistrale 110/110 con Lode — LABA Brescia',
      'UX research: competitor analysis, test utente, architettura conversazionale',
      'Front-end sviluppato in Vue.js con integrazione LLM',
      'Flow completo: scoperta prodotto → carrello → checkout in-chat',
    ],
    featured: true,
  },
  {
    slug: 'mita-museum',
    title: 'MITA — Museum Brand Identity',
    client: 'Progetto accademico',
    year: '2025',
    category: ['Brand Identity', 'Visual Identity', 'Architecture'],
    role: ['Brand Designer', 'Art Director'],
    stack: ['Adobe Photoshop', 'AI', 'Apple Keynote'],
    cover: `${B}/fa4804235104359.68d0fba061dfc.jpg`,
    gallery: [
      { src: `${B}/fa4804235104359.68d0fba061dfc.jpg`, alt: 'MITA — hero' },
      { src: `${B}/0471ce235104359.68d0fba064fde.jpg`, alt: 'MITA — logo system' },
      { src: `${B}/7d7980235104359.68d0fba0615b1.jpg`, alt: 'MITA — brand applications' },
      { src: `${B}/143237235104359.68d0fba062dec.jpg`, alt: 'MITA — poster' },
      { src: `${B}/9716be235104359.68d0fba063595.jpg`, alt: 'MITA — social' },
      { src: `${B}/b64e19235104359.68d0fba0625c8.jpg`, alt: 'MITA — identity' },
    ],
    url: 'https://www.behance.net/gallery/235104359/MITA-MUSEUM',
    excerpt: 'Brand identity completa per un museo: sistema visivo, advertising e social media.',
    description: 'MITA è un progetto di brand identity completa per un museo, che comprende la definizione del sistema visivo, le linee guida del brand, le applicazioni per advertising, social media e materiali promozionali. Il progetto combina architettura, co-creation e marketing in un\'identità visiva coerente.',
    highlights: [
      'Brand identity completa con sistema visivo',
      'Linee guida brand per advertising e social',
      'Applicazioni su poster e materiali promozionali',
      'Integrazione con linguaggio architettonico',
    ],
    featured: true,
  },
  {
    slug: 'motion-design-video',
    title: 'Motion Design — Video',
    client: 'Progetto accademico',
    year: '2025',
    category: ['Motion Graphics', 'Animation', 'Video'],
    role: ['Motion Designer', 'Animator'],
    stack: ['Adobe After Effects', 'Photoshop', 'Cinema 4D'],
    cover: `${BO}/ec5e7a237498571.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png`,
    gallery: [
      { src: `${BO}/ec5e7a237498571.Y3JvcCwxMzgwLDEwODAsMjcwLDA.png`, alt: 'Motion Design — frame 1' },
      { src: `${BO}/b3f7fc238170125.Y3JvcCwxMzgwLDEwODAsMzM0LDA.png`, alt: 'Motion Design — frame 2' },
    ],
    url: 'https://www.behance.net/gallery/235103681/MOTION-DESIGN-VIDEO',
    excerpt: 'Motion graphics e animazione 2D/character design con After Effects e Cinema 4D.',
    description: 'Progetto di motion design e video che esplora le possibilità dell\'animazione 2D, del character design e della motion graphics. Realizzato con Adobe After Effects e Cinema 4D, unisce concept creativo e tecnica di animazione in un prodotto video visivamente impattante.',
    highlights: [
      'Animazione 2D e motion graphics',
      'Character design originale',
      'Compositing video con After Effects',
      'Integrazione 3D con Cinema 4D',
    ],
    featured: false,
  },
  {
    slug: 'pinacoteca-brera',
    title: 'Pinacoteca di Brera — Restyling',
    client: 'Progetto accademico',
    year: '2025',
    category: ['Brand Identity', 'Visual Identity', 'Graphic Design'],
    role: ['Brand Designer', 'Art Director'],
    stack: ['Adobe Illustrator', 'InDesign', 'Photoshop'],
    cover: `${BO}/e15989235103219.68d0f72bafdef.jpeg`,
    gallery: [
      { src: `${BO}/e15989235103219.68d0f72bafdef.jpeg`, alt: 'Pinacoteca Brera — cover' },
      { src: `${BO}/ec8c08235103219.68d0f72ba4317.jpeg`, alt: 'Pinacoteca Brera — logo' },
      { src: `${BO}/5897a6235103219.68d0f72baa413.jpeg`, alt: 'Pinacoteca Brera — brand' },
      { src: `${BO}/857d69235103219.68d0f72ba4be0.jpeg`, alt: 'Pinacoteca Brera — poster' },
      { src: `${BO}/34f6e4235103219.68d0f72ba8642.jpeg`, alt: 'Pinacoteca Brera — social' },
      { src: `${BO}/3515bc235103219.68d0f72ba6097.jpeg`, alt: 'Pinacoteca Brera — applicazioni' },
    ],
    url: 'https://www.behance.net/gallery/235103219/Pinacoteca-di-Brera-restyling',
    excerpt: 'Restyling della brand identity della Pinacoteca di Brera: visual identity e social media.',
    description: 'Restyling della brand identity per la Pinacoteca di Brera, una delle più importanti gallerie d\'arte italiane. Il progetto ridisegna il sistema visivo, il logo, il poster design e le declinazioni per i social media, portando un linguaggio contemporaneo nel rispetto del patrimonio storico.',
    highlights: [
      'Restyling brand identity per istituzione culturale storica',
      'Sistema visivo rinnovato con identità contemporanea',
      'Poster design e materiali promozionali',
      'Social media marketing design',
    ],
    featured: true,
  },
  {
    slug: 'none-club',
    title: 'NONE-CLUB',
    client: 'Progetto personale',
    year: '2025',
    category: ['Brand Identity', 'Social Media', 'Graphic Design'],
    role: ['Brand Designer', 'Graphic Designer'],
    stack: ['Adobe Illustrator', 'Photoshop', 'AI'],
    cover: `${B}/c5eefb235102637.68d0f50dc772f.jpeg`,
    gallery: [
      { src: `${B}/c5eefb235102637.68d0f50dc772f.jpeg`, alt: 'NONE-CLUB — cover' },
      { src: `${B}/002ead235102637.68d0f50dc4f27.jpeg`, alt: 'NONE-CLUB — logo' },
      { src: `${B}/e35336235102637.68d0f50dc202c.jpeg`, alt: 'NONE-CLUB — social 1' },
      { src: `${B}/013f55235102637.68d0f50dbe207.jpeg`, alt: 'NONE-CLUB — social 2' },
      { src: `${B}/1f918f235102637.68d0f50dc11ee.jpeg`, alt: 'NONE-CLUB — brand' },
      { src: `${B}/9c693f235102637.68d0f50dc7bf3.jpeg`, alt: 'NONE-CLUB — applicazioni' },
    ],
    url: 'https://www.behance.net/gallery/235102637/NONE-CLUB',
    excerpt: 'Brand identity e visual identity per NONE-CLUB con social media post e advertising.',
    description: 'NONE-CLUB è un progetto di brand identity che include la progettazione del visual identity system, la creazione di contenuti per social media e materiali pubblicitari. Il progetto combina copywriting e design visivo in una comunicazione coerente e d\'impatto.',
    highlights: [
      'Brand identity e visual identity system',
      'Social media post design serie completa',
      'Advertising e materiali promozionali',
      'Copywriting integrato nel design',
    ],
    featured: false,
  },
  {
    slug: 'photographic-journey',
    title: 'My Photographic Journey',
    client: 'Portfolio personale',
    year: '2025',
    category: ['Photography', 'Post-Production'],
    role: ['Photographer', 'Photo Editor'],
    stack: ['Adobe Photoshop', 'Lightroom', 'Adobe Camera Raw', 'Luminar'],
    cover: `${B}/d401b2227151921.683ac211f1b80.jpg`,
    gallery: [
      { src: `${B}/d401b2227151921.683ac211f1b80.jpg`, alt: 'Photography — ritratto 1' },
      { src: `${B}/ff06b2227151921.683ac211f40b9.jpg`, alt: 'Photography — ritratto 2' },
      { src: `${B}/652995227151921.683ac211f2a1d.jpg`, alt: 'Photography — ritratto 3' },
      { src: `${B}/4c0e51227151921.683ac211efd5b.jpg`, alt: 'Photography — scena 1' },
      { src: `${B}/b9bb6c227151921.683ac211f3199.jpg`, alt: 'Photography — scena 2' },
      { src: `${B}/686fef227151921.683ac211f08c8.jpg`, alt: 'Photography — scena 3' },
      { src: `${B}/4c037a227151921.683ac211f22ae.jpg`, alt: 'Photography — beauty' },
      { src: `${B}/062205227151921.683ac35e7a0ee.jpg`, alt: 'Photography — outdoor' },
    ],
    url: 'https://www.behance.net/gallery/227151921/My-photographic-journey',
    excerpt: 'Raccolta fotografica personale: beauty photography e ritratti con post-produzione avanzata.',
    description: 'My Photographic Journey è una raccolta del mio percorso fotografico personale, con particolare focus sulla beauty photography e i ritratti. Ogni scatto è accompagnato da una post-produzione professionale con Lightroom, Adobe Camera Raw e Luminar.',
    highlights: [
      'Beauty photography e ritratti professionali',
      'Post-produzione avanzata con Lightroom e Camera Raw',
      'Ricerca estetica personale e sperimentazione stilistica',
      'Patente drone per riprese aeree certificate',
    ],
    featured: false,
  },
  {
    slug: 'airpods-pro-2',
    title: 'AirPods Pro 2 — 3D Web Experience',
    client: 'Progetto accademico — LABA Brescia',
    year: '2025',
    category: ['3D', 'Web Design', 'Product Showcase'],
    role: ['3D Artist', 'Web Designer'],
    stack: ['Figma', 'Webflow', 'Spline', 'Photoshop'],
    cover: `${B}/6c06dc224462475.6810925c89335.jpg`,
    gallery: [
      { src: `${B}/6c06dc224462475.6810925c89335.jpg`, alt: 'AirPods Pro 2 — hero' },
      { src: `${B}/5eebf9224462475.6810925c898c7.jpg`, alt: 'AirPods Pro 2 — 3D render' },
      { src: `${B}/3a364b224462475.6810a1a4241fa.jpg`, alt: 'AirPods Pro 2 — dettaglio' },
      { src: `${B}/b3ac03224462475.6810925c87e8b.jpg`, alt: 'AirPods Pro 2 — scroll section' },
      { src: `${B}/9a6c77224462475.6810925c88b9f.jpg`, alt: 'AirPods Pro 2 — features' },
      { src: `${B}/6d15b8224462475.6810925c876f3.jpg`, alt: 'AirPods Pro 2 — closing' },
    ],
    url: 'https://www.behance.net/gallery/224462475/AirPods-Pro-2-project',
    excerpt: 'Showcase web Apple-style: rendering 3D di AirPods Pro 2 in Spline integrato in Webflow con scroll animato.',
    description: 'Showcase web in stile Apple per AirPods Pro 2. Ho realizzato il rendering 3D dei modelli in Spline, ottimizzato gli asset per il web e costruito l\'esperienza in Webflow con scroll animato, parallasse e interazioni hover sulla sequenza prodotto.',
    highlights: [
      'Modellazione e rendering 3D in Spline',
      'Pipeline di esportazione ottimizzata per il web',
      'Animazione scroll con Webflow interactions',
      'Replica fedele del linguaggio visivo Apple product pages',
    ],
    featured: true,
  },
  {
    slug: 'design-system',
    title: 'Design System',
    client: 'Progetto accademico',
    year: '2025',
    category: ['Design System', 'Brand Identity', 'UI/UX'],
    role: ['UX/UI Designer', 'Brand Designer'],
    stack: ['Figma'],
    cover: `${B}/06fc13218652809.67a4bd9ac80b5.png`,
    gallery: [
      { src: `${B}/06fc13218652809.67a4bd9ac80b5.png`, alt: 'Design System — overview' },
      { src: `${B}/1f09dd218652809.67a4bd9ac5087.png`, alt: 'Design System — colori' },
      { src: `${B}/dd31f5218652809.67a4bd9ace3b4.png`, alt: 'Design System — tipografia' },
      { src: `${B}/93605a218652809.67a4bd9ac5bcb.png`, alt: 'Design System — componenti' },
      { src: `${B}/5709b4218652809.67a4bd9ac97d8.png`, alt: 'Design System — spacing' },
      { src: `${B}/817f38218652809.67a4bd9ac4b8a.png`, alt: 'Design System — icone' },
    ],
    url: 'https://www.behance.net/gallery/218652809/Design-System',
    excerpt: 'Design system completo in Figma: token, componenti, linee guida e brand identity.',
    description: 'Design system completo sviluppato in Figma. Il sistema include la definizione dei token di design (colore, tipografia, spacing, radius), una libreria di componenti riutilizzabili, le linee guida del brand e le regole di composizione delle interfacce.',
    highlights: [
      'Token di design: colore, tipografia, spacing, radius',
      'Libreria componenti completa e documentata in Figma',
      'Linee guida brand e regole di composizione',
      'Design scalabile per team e prodotti diversi',
    ],
    featured: false,
  },
  {
    slug: 'museo-della-carta',
    title: 'Museo della Carta — Website',
    client: 'Progetto accademico',
    year: '2024',
    category: ['Web Design', 'Brand Identity', 'UX/UI'],
    role: ['UX/UI Designer', 'Web Designer'],
    stack: ['Figma'],
    cover: `${B}/993f17202375559.66850c8924ac0.jpg`,
    gallery: [
      { src: `${B}/993f17202375559.66850c8924ac0.jpg`, alt: 'Museo della Carta — homepage' },
      { src: `${B}/c7a2b2202375559.66850c89250b3.jpg`, alt: 'Museo della Carta — about' },
      { src: `${B}/c44105202375559.66850c89237ac.jpg`, alt: 'Museo della Carta — collezioni' },
      { src: `${B}/ce0188202375559.66850c89242e0.jpg`, alt: 'Museo della Carta — eventi' },
      { src: `${B}/54d11e202375559.66850c892598d.jpg`, alt: 'Museo della Carta — contatti' },
    ],
    url: 'https://www.behance.net/gallery/202375559/Museo-della-Carta-website',
    excerpt: 'Website design per il Museo della Carta: UX research, wireframe e UI completa.',
    description: 'Progetto di web design per il Museo della Carta, con approccio completo che parte dall\'UX research e arriva alla definizione dell\'interfaccia grafica finale. Il sito comunica il patrimonio culturale del museo attraverso un\'esperienza digitale immersiva e accessibile.',
    highlights: [
      'UX research e definizione architettura informativa',
      'Wireframe e prototipo navigabile in Figma',
      'UI design completa con sistema visivo coerente',
      'Accessibilità e performance come priorità',
    ],
    featured: true,
  },
  {
    slug: 'webapp-environmental',
    title: 'Webapp Environmental Education',
    client: 'Progetto accademico',
    year: '2024',
    category: ['Web App', 'UX/UI', 'Brand Identity'],
    role: ['UX/UI Designer', 'Art Director'],
    stack: ['Adobe Photoshop', 'InDesign', 'Illustrator', 'Figma', 'Miro'],
    cover: `${B}/cbdb80202374805.66850a0550f3f.jpg`,
    gallery: [
      { src: `${B}/cbdb80202374805.66850a0550f3f.jpg`, alt: 'Webapp Environmental — hero' },
      { src: `${B}/83925d202374805.66850a05516b4.jpg`, alt: 'Webapp Environmental — dashboard' },
      { src: `${B}/9638eb202374805.66850a0551db8.jpg`, alt: 'Webapp Environmental — sezione 1' },
      { src: `${B}/9320ab202374805.66850a054f0f2.jpg`, alt: 'Webapp Environmental — sezione 2' },
      { src: `${B}/073ef6202374805.66850a054f812.png`, alt: 'Webapp Environmental — brand' },
      { src: `${B}/17d980202374805.66850a054ff7d.jpg`, alt: 'Webapp Environmental — mobile' },
    ],
    url: 'https://www.behance.net/gallery/202374805/Webapp-environmental-education',
    excerpt: 'Web app per l\'educazione ambientale: UX research, brand identity e UI completa.',
    description: 'Web app dedicata all\'educazione ambientale, con un approccio che unisce UX research (Miro), brand identity e UI design (Figma). L\'app mira a sensibilizzare gli utenti sui temi ambientali attraverso un\'esperienza interattiva e coinvolgente.',
    highlights: [
      'UX research con mappe di empatia e user journey',
      'Brand identity dedicata al tema ambientale',
      'UI design responsive e accessibile',
      'Art direction coerente su tutti i touchpoint',
    ],
    featured: false,
  },

  // ─── APDESIGN.ALTERVISTA.ORG ─────────────────────────────────────────────────
  {
    slug: 'citta-nel-deserto',
    title: 'La città nel deserto',
    client: 'Accademia di Belle Arti di Brescia Santa Giulia',
    year: '2022',
    category: ['Matte Painting', 'Digital Art', 'Compositing'],
    role: ['Digital Artist', 'Compositor'],
    stack: ['Adobe Photoshop', 'Compositing', 'Color Grading'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/1-scaled.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/1-scaled.jpg', alt: 'La città nel deserto' },
    ],
    url: 'https://apdesign.altervista.org/matte-painting/',
    excerpt: 'Compositing digitale che ricrea un paesaggio urbano immerso nel deserto, con correzione cromatica avanzata.',
    description: 'Opera di matte painting realizzata per il corso di Photoshop II all\'Accademia di Belle Arti di Brescia Santa Giulia. Paesaggio fantastico che unisce una città moderna con un ambiente desertico tramite tecniche avanzate di compositing e correzione cromatica.',
    highlights: [
      'Compositing multi-layer con maschere avanzate',
      'Color grading per coerenza cromatica',
      'Gestione della luce e delle ombre per integrazione realistica',
    ],
    featured: true,
  },
  {
    slug: 'naufragio',
    title: 'Naufragio',
    client: 'Accademia di Belle Arti di Brescia Santa Giulia',
    year: '2022',
    category: ['Matte Painting', 'Digital Art', 'Storytelling'],
    role: ['Digital Artist', 'Compositor'],
    stack: ['Adobe Photoshop', 'Compositing'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/2-1.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/2-1.jpg', alt: 'Naufragio — compositing' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/5-1280x720.jpg', alt: 'Naufragio — scena principale' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/4-1280x982.jpg', alt: 'Naufragio — variante compositing' },
    ],
    url: 'https://apdesign.altervista.org/matte-painting/',
    excerpt: 'Matte painting narrativo: una ragazza avventurosa affronta il naufragio della sua nave da crociera.',
    description: 'Opera di matte painting con forte carica narrativa. L\'opera racconta la storia di una ragazza avventurosa che affronta il naufragio della sua nave. Il compositing unisce fotografie oceaniche, architettura navale e figure umane in una scena drammatica.',
    highlights: [
      'Narrazione visiva con atmosfera drammatica',
      'Effetti atmosferici: pioggia, nebbia e luci',
      'Integrazione di elementi architettonici con ambiente naturale',
    ],
    featured: false,
  },
  {
    slug: 'isola-che-non-ce',
    title: "L'isola che non c'è",
    client: 'Accademia di Belle Arti di Brescia Santa Giulia',
    year: '2022',
    category: ['Matte Painting', 'Fantasy', 'Compositing'],
    role: ['Digital Artist', 'Compositor'],
    stack: ['Adobe Photoshop', 'Compositing', 'Digital Painting'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/3.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/3.jpg', alt: "L'isola che non c'è" },
    ],
    url: 'https://apdesign.altervista.org/matte-painting/',
    excerpt: "Isola fantasy creata attraverso tecniche di compositing da immagini di riferimento reali.",
    description: "Isola immaginaria composta da fotografie reali: montagne, cascate, vegetazione tropicale e architetture in un ambiente sospeso tra realtà e fantasia.",
    highlights: [
      'Creazione ambiente fantasy da fotografie reali',
      'Blend avanzato tra biomi diversi',
      'Palette cromatica sognante e coerente',
    ],
    featured: false,
  },
  {
    slug: 'samurai',
    title: 'Samurai',
    client: 'Accademia di Belle Arti di Brescia Santa Giulia',
    year: '2022',
    category: ['Matte Painting', 'Action', 'Narrative Art'],
    role: ['Digital Artist', 'Compositor'],
    stack: ['Adobe Photoshop', 'Compositing', 'Retouching'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/4.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/4.jpg', alt: 'Samurai — compositing' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/1-1280x720.jpg', alt: 'Samurai — scena principale' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/2-1.jpg', alt: 'Samurai — variante compositing' },
    ],
    url: 'https://apdesign.altervista.org/matte-painting/',
    excerpt: 'Matte painting action: un samurai che cerca vendetta per la morte dei compagni.',
    description: 'Opera di matte painting ad alto impatto narrativo. Scena di un samurai in viaggio di vendetta: paesaggi giapponesi, figure in costume e ambientazioni storiche con palette drammatica.',
    highlights: [
      'Narrazione cinematografica con palette drammatica',
      'Compositing figure in costume storico',
      'Effetti luce e nebbia per profondità atmosferica',
    ],
    featured: false,
  },
  {
    slug: 'difesa-della-natura',
    title: 'Difesa della natura',
    client: 'Accademia di Belle Arti di Brescia Santa Giulia',
    year: '2022',
    category: ['Matte Painting', 'Environmentalism', 'Fantasy'],
    role: ['Digital Artist', 'Compositor'],
    stack: ['Adobe Photoshop', 'Compositing'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/5.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/5.jpg', alt: 'Difesa della natura — compositing' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/11/5.jpg', alt: 'Difesa della natura — dettaglio' },
    ],
    url: 'https://apdesign.altervista.org/matte-painting/',
    excerpt: 'Una ragazza e la sua fedele aquila combattono insieme per difendere la natura.',
    description: 'Opera di matte painting con messaggio ambientalista. Una giovane guerriera e la sua aquila difendono la natura minacciata. Palette di verdi e ocra dominanti.',
    highlights: [
      'Messaggio ambientalista con narrazione visiva',
      'Compositing figura umana + rapace in volo',
      'Palette naturale con verdi e ocra dominanti',
    ],
    featured: false,
  },
  {
    slug: 'east-vs-west',
    title: 'East vs West Coast',
    client: 'Progetto accademico',
    year: '2022',
    category: ['Brochure Design', 'Editorial', 'Graphic Design'],
    role: ['Graphic Designer', 'Art Director'],
    stack: ['Adobe InDesign', 'Photoshop', 'Illustrator'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/3-4-scaled.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-17-alle-12.06.09.png', alt: 'East vs West — apertura' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-17-alle-12.06.23.png', alt: 'East vs West — layout' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/3-4-scaled.jpg', alt: 'East vs West — copertina' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/1-4-scaled.jpg', alt: 'East vs West — spread' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/3-5-scaled.jpg', alt: 'East vs West — interno' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/3334004.jpg', alt: 'East vs West — Tupac' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/291991.jpg', alt: 'East vs West — Notorious B.I.G.' },
    ],
    url: 'https://apdesign.altervista.org/brochure/east-vs-west/',
    excerpt: 'Brochure sulla rivalità tra East e West Coast hip-hop: Death Row vs Bad Boy Records.',
    description: "Brochure editoriale sulla storica rivalità hip-hop anni '90, tra Death Row Records e Bad Boy Records, Tupac e Notorious B.I.G. Timeline degli eventi con forte identità tipografica.",
    highlights: [
      "Documentazione storica rivalità hip-hop anni '90",
      'Layout editoriale con forte identità tipografica',
      'Ricerca fotografica e iconografica',
    ],
    featured: true,
  },
  {
    slug: 'first-things-first',
    title: 'First Things First',
    client: 'Progetto accademico',
    year: '2022',
    category: ['Brochure Design', 'Manifesto', 'Graphic Design'],
    role: ['Graphic Designer', 'Art Director'],
    stack: ['Adobe InDesign', 'Photoshop', 'Typography'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/def-2-scaled.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/def-2-scaled.jpg', alt: 'First Things First — copertina' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/2-7-scaled.jpg', alt: 'First Things First — spread' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/michal-bajus-P9LTNN1GJqk-unsplash-scaled.jpg', alt: 'First Things First — fotografia' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/nikita-kachanovsky-g-YiX8ynmnY-unsplash-scaled.jpg', alt: 'First Things First — composizione' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/82980b5d1d471e18da5c1e820e2deaf2.jpg', alt: 'First Things First — Bruno Munari' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Enzo_Mari_1974.jpg', alt: 'First Things First — Enzo Mari' },
    ],
    url: 'https://apdesign.altervista.org/brochure/first-things-first/',
    excerpt: "Brochure-manifesto sull'etica del graphic designer: da Munari a Mari, dal commercio all'impatto sociale.",
    description: "Brochure-manifesto sull'etica professionale del designer. Critica al design commerciale con invito a dedicare il talento a sfide sociali e ambientali. Ispirata a Bruno Munari e Enzo Mari.",
    highlights: [
      "Manifesto per l'etica del design con riferimenti a Munari e Mari",
      'Layout tipografico minimalista e assertivo',
      "Call to action per un design d'impatto sociale",
    ],
    featured: true,
  },
  {
    slug: 'cookbook',
    title: 'Cookbook',
    client: 'Progetto personale',
    year: '2022',
    category: ['Book Design', 'Editorial', 'Graphic Design'],
    role: ['Graphic Designer', 'Editor'],
    stack: ['Adobe InDesign', 'Photoshop', 'Editorial Design'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/gaelle-marcel-GaLWM8dX73U-unsplash-scaled.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/gaelle-marcel-GaLWM8dX73U-unsplash-scaled.jpg', alt: 'Cookbook — cover food' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/jonathan-borba-uB7q7aipU2o-unsplash-scaled.jpg', alt: 'Cookbook — cucina' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/1-6-scaled.jpg', alt: 'Cookbook — impaginazione' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/3-7-scaled.jpg', alt: 'Cookbook — spread interno' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/wp2993551-gordon-ramsay-hd-wallpapers.jpg', alt: 'Cookbook — Gordon Ramsay' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-17-alle-14.07.13.png', alt: 'Cookbook — Cannavacciuolo' },
    ],
    url: 'https://apdesign.altervista.org/brochure/cookbook/',
    excerpt: 'Libro di cucina personale che esplora il legame tra viaggio, cultura e gastronomia.',
    description: 'Book design per un libro di cucina personale. Storytelling narrativo, fotografia food, sezioni storiche sulla tradizione culinaria (Maestro Martino, Scappi, Vatel) e citazioni di Ramsay e Cannavacciuolo.',
    highlights: [
      'Book design con layout editoriale caldo e narrativo',
      'Fotografia food integrata nel testo',
      'Sezione storica sulla tradizione gastronomica europea',
    ],
    featured: false,
  },
  {
    slug: 'reteye',
    title: 'Reteye — Design per la cecità ai colori',
    client: 'Tesi triennale — Accademia Santa Giulia (Brescia)',
    year: '2023',
    category: ['Brand Identity', 'Accessibility', 'Social Design', 'Thesis'],
    role: ['Brand Designer', 'Researcher', 'Art Director'],
    stack: ['Adobe Creative Suite', 'Illustrator', 'InDesign', 'Photoshop'],
    cover: 'https://reteye.altervista.org/wp-content/uploads/2023/06/4-orizzontale-scaled.jpg',
    gallery: [
      { src: 'https://reteye.altervista.org/wp-content/uploads/2023/06/Reteye-logo.png', alt: 'Reteye — logo' },
      { src: 'https://reteye.altervista.org/wp-content/uploads/2023/06/4-orizzontale-scaled.jpg', alt: 'Reteye — brand identity' },
      { src: 'https://reteye.altervista.org/wp-content/uploads/2023/06/STUDIO_1A-scaled.jpg', alt: 'Reteye — applicazioni brand' },
      { src: 'https://reteye.altervista.org/wp-content/uploads/2023/06/eticehtta-rosso-2-2-scaled.jpg', alt: 'Reteye — etichetta' },
      { src: 'https://reteye.altervista.org/wp-content/uploads/2023/06/55-scaled.jpg', alt: 'Reteye — materiali 1' },
      { src: 'https://reteye.altervista.org/wp-content/uploads/2023/06/44-scaled.jpg', alt: 'Reteye — materiali 2' },
    ],
    url: 'https://reteye.altervista.org',
    excerpt: 'Tesi triennale 110L/100: azienda di design per la sensibilizzazione sulla cecità ai colori.',
    description: "Reteye è il progetto di tesi della Laurea triennale in Graphic Design (110L/100) all'Accademia Santa Giulia di Brescia. Azienda di design dedicata alla sensibilizzazione sulla cecità ai colori: brand identity completa, editoriale, social, packaging e web. Tra i migliori 50 in Europa all'ICHEP.",
    highlights: [
      "Laurea triennale 110L/100 — Accademia Santa Giulia Brescia",
      "Tra i migliori 50 progetti in Europa all'ICHEP",
      'Brand identity completa + sistema editoriale',
      'Impatto sociale su accessibilità cromatica',
    ],
    featured: true,
  },

  // ─── APDESIGN — LOGO DESIGN ──────────────────────────────────────────────────
  {
    slug: 'cultura-della-cura',
    title: 'Cultura della Cura — Logo Design',
    client: 'Progetto accademico — Accademia Santa Giulia Brescia',
    year: '2022',
    category: ['Logo Design', 'Brand Identity', 'Graphic Design'],
    role: ['Brand Designer', 'Graphic Designer'],
    stack: ['Adobe Illustrator', 'Photoshop'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/8167736-scaled.jpg',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/8167736-scaled.jpg', alt: 'Cultura della Cura — concept' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.02.38.png', alt: 'Cultura della Cura — logo' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.02.46.png', alt: 'Cultura della Cura — varianti' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.03.31.png', alt: 'Cultura della Cura — colori' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.04.19.png', alt: 'Cultura della Cura — applicazione 1' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.04.09.png', alt: 'Cultura della Cura — applicazione 2' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.04.32.png', alt: 'Cultura della Cura — applicazione 3' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.04.41.png', alt: 'Cultura della Cura — applicazione 4' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-14-alle-15.05.12.png', alt: 'Cultura della Cura — presentazione' },
    ],
    url: 'https://apdesign.altervista.org/homepage/logos/cultura-della-cura/',
    excerpt: 'Logo design per associazione: pittogramma a loto simbolo di benessere e rinascita.',
    description: 'Logo design per l\'associazione "Cultura della Cura". Il simbolo è un pittogramma che evoca i valori dell\'associazione: tre sfere a forma di chakra compongono un fiore di loto, simbolo di benessere personale e rinascita. La palette cromatica e il concept visivo riflettono i valori di cura, salute e crescita spirituale rivolti a studenti, pazienti oncologici e operatori sanitari.',
    highlights: [
      'Pittogramma loto da tre sfere — simbolismo chakra',
      'Target triplice: studenti, pazienti oncologici, operatori sanitari',
      'Sistema di colori per benessere e rinascita',
    ],
    featured: false,
  },
  {
    slug: 'friza',
    title: 'Azienda Agricola Friza — Logo Design',
    client: 'Progetto accademico — Accademia Santa Giulia Brescia',
    year: '2022',
    category: ['Logo Design', 'Brand Identity', 'Graphic Design'],
    role: ['Brand Designer', 'Graphic Designer'],
    stack: ['Adobe Illustrator', 'Photoshop'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.14.31.png',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.14.31.png', alt: 'Friza — logo' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.16.42.png', alt: 'Friza — concept' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.16.57.png', alt: 'Friza — varianti' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.18.44.png', alt: 'Friza — colori' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.17.49.png', alt: 'Friza — applicazione 1' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.17.13.png', alt: 'Friza — applicazione 2' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.15.54.png', alt: 'Friza — applicazione 3' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.17.39.png', alt: 'Friza — applicazione 4' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.17.59.png', alt: 'Friza — presentazione' },
    ],
    url: 'https://apdesign.altervista.org/homepage/logos/friza/',
    excerpt: 'Logo per azienda agricola montana di Scanzorosciiate: freccia sinuosa che unisce bottiglia e calice.',
    description: 'Logo design per l\'Azienda Agricola Friza di Scanzorosciiate (BG). Il naming deriva dal dialetto bergamasco "friza" = freccia, riferimento al tortuoso sentiero montano che porta all\'azienda. Il marchio combina una bottiglia e un calice uniti da una freccia sinuosa, simbolo di qualità e superamento dei limiti. I colori richiamano il terroir del vigneto di Scanzo, dove l\'azienda produce vini e grappe.',
    highlights: [
      'Naming da dialetto bergamasco: "friza" = freccia',
      'Simbolo bottiglia + calice + freccia sinuosa',
      'Palette ispirata al terroir del vigneto di Scanzo',
    ],
    featured: false,
  },
  {
    slug: 'ichep-2022',
    title: 'ICHEP 2022 — Logo Design',
    client: 'Progetto accademico — Accademia Santa Giulia Brescia',
    year: '2022',
    category: ['Logo Design', 'Brand Identity', 'Event Branding'],
    role: ['Brand Designer', 'Graphic Designer'],
    stack: ['Adobe Illustrator', 'Photoshop'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.11.06.png',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.11.06.png', alt: 'ICHEP 2022 — logo' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.16.31.png', alt: 'ICHEP 2022 — concept' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.16.22.png', alt: 'ICHEP 2022 — varianti' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.16.38.png', alt: 'ICHEP 2022 — colori' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.14.19.png', alt: 'ICHEP 2022 — applicazione 1' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.14.26.png', alt: 'ICHEP 2022 — applicazione 2' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.14.33.png', alt: 'ICHEP 2022 — applicazione 3' },
    ],
    url: 'https://apdesign.altervista.org/homepage/logos/ichep/',
    excerpt: 'Logo per conferenza ICHEP 2022 a Bologna: orbite atomiche e torri simbolo della città.',
    description: 'Logo design per la conferenza internazionale ICHEP 2022 (6–13 luglio, Bologna), realizzato in collaborazione con l\'Accademia Santa Giulia di Brescia. Il marchio usa due orbite che circondano un elemento centrale raffigurante le torri Garisenda e Asinelli come struttura atomica simbolica. I colori istituzionali di Bologna: blu per la scienza e l\'oceano, rosso per energia e vitalità.',
    highlights: [
      'Logotipo per conferenza internazionale di fisica ICHEP 2022',
      'Simbolo: orbite atomiche + torri Garisenda e Asinelli',
      'Palette: blu scienza + rosso energia — colori di Bologna',
    ],
    featured: false,
  },
  {
    slug: 'legacy',
    title: 'Legacy — Logo Design',
    client: 'Progetto accademico — Accademia Santa Giulia Brescia',
    year: '2022',
    category: ['Logo Design', 'Brand Identity', 'Graphic Design'],
    role: ['Brand Designer', 'Graphic Designer'],
    stack: ['Adobe Illustrator', 'Photoshop'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.49.12.png',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.49.12.png', alt: 'Legacy — logo' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.51.39.png', alt: 'Legacy — concept infinito' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.50.57.png', alt: 'Legacy — varianti' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.50.40.png', alt: 'Legacy — colori' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.51.10.png', alt: 'Legacy — applicazione 1' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.51.27.png', alt: 'Legacy — applicazione 2' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.51.44.png', alt: 'Legacy — applicazione 3' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-12.55.09.png', alt: 'Legacy — presentazione' },
    ],
    url: 'https://apdesign.altervista.org/homepage/logos/legacy/',
    excerpt: 'Logo per brand caffè: simbolo dell\'infinito per continuità e lascito senza tempo.',
    description: 'Logo design per "Legacy", brand nel settore del caffè. Il concept nasce dal simbolo dell\'infinito, metafora di una continuità che si ripete senza fine. Il payoff "Luminous lovely legacy" rafforza l\'idea di un marchio destinato a durare. I colori dinamici comunicano modernità e distinguono il brand sul mercato del caffè premium.',
    highlights: [
      'Simbolo dell\'infinito come metafora di continuità',
      'Payoff: "Luminous lovely legacy"',
      'Target: aziende caffè, appassionati, distributori macchine espresso',
    ],
    featured: false,
  },
  {
    slug: 'correndo-coop',
    title: 'Correndo Coop — Logo Design',
    client: 'Progetto accademico — Brand Design II, Accademia Santa Giulia Brescia',
    year: '2022',
    category: ['Logo Design', 'Brand Identity', 'Sportswear'],
    role: ['Brand Designer', 'Graphic Designer'],
    stack: ['Adobe Illustrator', 'Photoshop'],
    cover: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.36.23.png',
    gallery: [
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Screenshot-2022-12-15-alle-13.36.23.png', alt: 'Correndo Coop — logo' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/ShoesBOX.jpg', alt: 'Correndo Coop — packaging scarpe' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/scarpe-unisex-nere1-scaled.jpg', alt: 'Correndo Coop — scarpe running' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Top-black.jpg', alt: 'Correndo Coop — top' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Donna-staff-scaled.jpg', alt: 'Correndo Coop — staff femminile' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Donna-short-black-scaled.jpg', alt: 'Correndo Coop — short running' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/2-bottel-black-scaled.jpg', alt: 'Correndo Coop — borracce' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Sacca-nera-scaled.jpg', alt: 'Correndo Coop — sacca' },
      { src: 'https://apdesign.altervista.org/wp-content/uploads/2022/12/Calzini-scaled.jpg', alt: 'Correndo Coop — calzini' },
    ],
    url: 'https://apdesign.altervista.org/homepage/logos/correndo/',
    excerpt: 'Private label sportswear per Coop Italia: logo e applicazioni su abbigliamento running.',
    description: 'Logo design e brand system per "Correndo Coop", nuova private label sportswear di Coop Italia specializzata nel running. Il naming deriva dall\'italiano "correndo", che enfatizza movimento e dinamismo. Il logo è composto da quattro elementi: wordmark "correndo", segno visivo che rappresenta la traiettoria del movimento, tagline e marchio Coop GDO. Le applicazioni coprono l\'intera gamma prodotto: scarpe, abbigliamento e accessori.',
    highlights: [
      'Private label sportswear per Coop Italia — settore running',
      'Logo a quattro elementi: wordmark + segno movimento + tagline + Coop',
      'Brand applications complete: scarpe, abbigliamento, accessori',
    ],
    featured: false,
  },
]

export const featuredProjects = projects.filter((p) => p.featured)
